### ISSUE TITLE
Suggestion for tokenizing a string

### ISSUE THREAD

**Issue by aroberge** [asmeurer/brown-water-python#1]
First of all, thank you for writing this. I just read through it and found it very easy to follow.

For tokenizing a string, you wrote a helper function to convert to bytes. In my own code, I found that I could bypass this step and use:

```py
import tokenize
from io import StringIO

for tok in tokenize.generate_tokens(StringIO(source).readline):
    pass
```

I do realize that `generate_tokens` no longer appear in the official documentation but it is a public function that used to be documented, is used in many projects, and I doubt very much that it would stop being supported. Of course, feel free to ignore this suggestion. :-)

**Comment by asmeurer** [comment]
I think you are right. It's part of `tokenize.__all__`, so that for me makes it part of the public API, even if it isn't documented.

From reading the tokenize code, if the code has an encoding cookie, it will be ignored with string input, because the string is already encoded. Of course, going from string to bytes here is pointless if you do already have a string, because it is already encoded. Probably if you are reading from a file or stream it is better to read it as bytes and use `tokenize`.  I'll play with it a bit and see about updating it. Or pull requests are welcome. 

IIRC, currently there are some issues with the build because some of the Sphinx extensions are broken. So I think we might need to pin some older versions if they haven't been fixed upstream yet (I think they haven't).

**Comment by asmeurer** [comment]
Also a large part of the document isn't technically considered API, in the sense that it could change in future versions (they even changed how [`NEWLINE`](https://www.asmeurer.com/brown-water-python/tokens.html#newline) works in a patch version). But the point of the document is to document how things work for the given Python versions, and if things change, it will need to be updated. So I think documenting `generate_tokens` is fine.

**Comment by aroberge** [comment]
Sorry about the pull request: you are a better writer than I am and better positioned to determine where this information should go in your document.

**Comment by asmeurer** [comment]
That's fine. I might not get around to it any time soon, but the next time I look at this project I'll take a look at adding this.

**Comment by asmeurer** [comment]
I've been doing some cleanups here with the 3.11 release and I finally got around to implementing this. 

I've added information about generate_tokens() at https://github.com/asmeurer/brown-water-python/pull/8. Note that I am going to keep all the examples throughout using `tokenize`. The reason is that for a typical use-case, i.e., reading from a file, you should use `tokenize` and not `generate_tokens` as only the former will detect the encoding correctly. `generate_tokens` is primarily useful if you are working interactively, or only with Python strings that are already encoded. It also doesn't emit the `ENCODING` token, which is why I want to keep the examples using `tokenize`. Also sometimes `ENCODING` is useful to have as a guaranteed first token, e.g., it makes it much simpler to implement a sliding window loop with one token lookahead.
